# application.yml
client:
  #  url: ${local.ip}:3000
  url: http://localhost:3000

server:
  #  url:  ${local.ip}:8080
  url: http://localhost:8080
  tomcat:
    uri-encoding: UTF-8

# application.yml
data-go-kr:
  base-url: http://api.data.go.kr/openapi
  service-key: "Dd2b7l%2FQ4H3naPkEspcUPA%2B7HSR4BklxRJYVpHqm71wzVDjmNWx53FTR2YXLX%2BHPB69tYQCE6T8RHEFEoVdFCg%3D%3D"  # ← 인코딩된 키 1번만 지정
  default-params:
    type: json
    numOfRows: 100
  apis:
    food:      { path: /tn_pubr_public_nutri_food_info_api }
    material:  { path: /tn_pubr_public_nutri_material_info_api }
    processed: { path: /tn_pubr_public_nutri_process_info_api }
    approved:  { path: /tn_pubr_public_nutri_info_api}

# Spring 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  sql:
    init:
      mode: always
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update